CREATE TABLE IF NOT EXISTS `BancoSangre` (
    `CREATE_DATABASE_IF_NOT_EXISTS_bancosangre` VARCHAR(87) CHARACTER SET utf8,
    `Column_2` VARCHAR(14) CHARACTER SET utf8,
    `Column_3` INT
);
INSERT INTO `BancoSangre` VALUES ('USE bancosangre;',NULL,NULL),
	(NULL,NULL,NULL),
	(NULL,NULL,NULL),
	('-- Tabla para almacenar información común de usuarios',NULL,NULL),
	('CREATE TABLE Usuarios (',NULL,NULL),
	('    id_usuario INT PRIMARY KEY',NULL,NULL),
	('    nombre VARCHAR(50)',NULL,NULL),
	('    correo_electronico VARCHAR(50)',NULL,NULL),
	('    contrasena VARCHAR(50)',NULL,NULL),
	(');',NULL,NULL),
	(NULL,NULL,NULL),
	('-- Tabla para almacenar información de pacientes',NULL,NULL),
	('CREATE TABLE Pacientes (',NULL,NULL),
	('    id_paciente INT PRIMARY KEY',NULL,NULL),
	('    id_usuario INT UNIQUE',NULL,NULL),
	('    genero VARCHAR(10)',NULL,NULL),
	('    edad INT',NULL,NULL),
	('    tipo_sangre VARCHAR(5)',NULL,NULL),
	('    ultima_transfusion DATE',NULL,NULL),
	('    historial_medico TEXT',NULL,NULL),
	('    FOREIGN KEY (id_usuario) REFERENCES Usuarios(id_usuario)',NULL,NULL),
	(');',NULL,NULL),
	(NULL,NULL,NULL),
	('-- Tabla para almacenar información de donantes',NULL,NULL),
	('CREATE TABLE Donantes (',NULL,NULL),
	('    id_donante INT PRIMARY KEY',NULL,NULL),
	('    id_usuario INT UNIQUE',NULL,NULL),
	('    genero VARCHAR(10)',NULL,NULL),
	('    edad INT',NULL,NULL),
	('    tipo_sangre VARCHAR(5)',NULL,NULL),
	('    ultima_donacion DATE',NULL,NULL),
	('    FOREIGN KEY (id_usuario) REFERENCES Usuarios(id_usuario)',NULL,NULL),
	(');',NULL,NULL),
	(NULL,NULL,NULL),
	('-- Tabla para almacenar información de bancos de sangre',NULL,NULL),
	('CREATE TABLE BancosDeSangre (',NULL,NULL),
	('    id_banco_sangre INT PRIMARY KEY',NULL,NULL),
	('    nombre VARCHAR(50)',NULL,NULL),
	('    direccion VARCHAR(100)',NULL,NULL),
	('    telefono VARCHAR(15)',NULL,NULL),
	(');',NULL,NULL),
	(NULL,NULL,NULL),
	('-- Tabla para almacenar información de hospitales',NULL,NULL),
	('CREATE TABLE Hospitales (',NULL,NULL),
	('    id_hospital INT PRIMARY KEY',NULL,NULL),
	('    nombre VARCHAR(50)',NULL,NULL),
	('    direccion VARCHAR(100)',NULL,NULL),
	('    telefono VARCHAR(15)',NULL,NULL),
	(');',NULL,NULL),
	(NULL,NULL,NULL),
	('-- Tabla para almacenar información de usuarios del hospital (médicos/enfermeros)',NULL,NULL),
	('CREATE TABLE UsuariosHospital (',NULL,NULL),
	('    id_usuario_hospital INT PRIMARY KEY',NULL,NULL),
	('    id_usuario INT UNIQUE',NULL,NULL),
	('    id_hospital INT',NULL,NULL),
	('    rol VARCHAR(20) CHECK (rol IN (''Medico''',' ''Enfermero''))',NULL),
	('    FOREIGN KEY (id_usuario) REFERENCES Usuarios(id_usuario)',NULL,NULL),
	('    FOREIGN KEY (id_hospital) REFERENCES Hospitales(id_hospital)',NULL,NULL),
	(');',NULL,NULL),
	(NULL,NULL,NULL),
	('-- Tabla para almacenar información de administradores de hospitales y bancos de sangre',NULL,NULL),
	('CREATE TABLE Administradores (',NULL,NULL),
	('    id_administrador INT PRIMARY KEY',NULL,NULL),
	('    id_usuario INT UNIQUE',NULL,NULL),
	('    id_hospital INT',NULL,NULL),
	('    id_banco_sangre INT',NULL,NULL),
	('    FOREIGN KEY (id_usuario) REFERENCES Usuarios(id_usuario)',NULL,NULL),
	('    FOREIGN KEY (id_hospital) REFERENCES Hospitales(id_hospital)',NULL,NULL),
	('    FOREIGN KEY (id_banco_sangre) REFERENCES BancosDeSangre(id_banco_sangre)',NULL,NULL),
	(');',NULL,NULL),
	(NULL,NULL,NULL),
	(NULL,NULL,NULL),
	(NULL,NULL,NULL),
	('-- Tabla para almacenar información de campañas de sangre',NULL,NULL),
	('CREATE TABLE CampanasDeSangre (',NULL,NULL),
	('    id_campana_sangre INT PRIMARY KEY',NULL,NULL),
	('    nombre VARCHAR(50)',NULL,NULL),
	('    fecha_inicio DATE',NULL,NULL),
	('    fecha_fin DATE',NULL,NULL),
	('    id_banco_sangre INT',NULL,NULL),
	('    FOREIGN KEY (id_banco_sangre) REFERENCES BancosDeSangre(id_banco_sangre)',NULL,NULL),
	(');',NULL,NULL),
	(NULL,NULL,NULL),
	('-- Tabla para almacenar donaciones de sangre',NULL,NULL),
	('CREATE TABLE DonacionesDeSangre (',NULL,NULL),
	('    id_donacion_sangre INT PRIMARY KEY',NULL,NULL),
	('    id_usuario INT',NULL,NULL),
	('    id_campana_sangre INT',NULL,NULL),
	('    fecha_donacion DATE',NULL,NULL),
	('    FOREIGN KEY (id_usuario) REFERENCES Usuarios(id_usuario)',NULL,NULL),
	('    FOREIGN KEY (id_campana_sangre) REFERENCES CampanasDeSangre(id_campana_sangre)',NULL,NULL),
	(');',NULL,NULL),
	(NULL,NULL,NULL),
	('-- Tabla para almacenar información médica de los pacientes',NULL,NULL),
	('CREATE TABLE InformacionMedica (',NULL,NULL),
	('    id_informacion_medica INT PRIMARY KEY',NULL,NULL),
	('    id_paciente INT',NULL,NULL),
	('    historial_medico TEXT',NULL,NULL),
	('    FOREIGN KEY (id_paciente) REFERENCES Pacientes(id_paciente)',NULL,NULL),
	(');',NULL,NULL),
	(NULL,NULL,NULL),
	('-- Relacionar médicos y enfermeros con hospitales',NULL,NULL),
	('CREATE TABLE PersonalHospital (',NULL,NULL),
	('    id_usuario_hospital INT',NULL,NULL),
	('    id_hospital INT',NULL,NULL),
	('    FOREIGN KEY (id_usuario_hospital) REFERENCES UsuariosHospital(id_usuario_hospital)',NULL,NULL),
	('    FOREIGN KEY (id_hospital) REFERENCES Hospitales(id_hospital)',NULL,NULL),
	('    PRIMARY KEY (id_usuario_hospital',' id_hospital)',NULL),
	(');',NULL,NULL);
